function [fdData] = loadFdData(fPath)
% Loads a raw data .txt file generated by the BIRRS system, returns
% the measured complex S-parameters in the frequency domain
%
% Parameters
% ----------
% fPath : str
%   Path to the data file to be loaded
%
% Returns
% -------
% fdData : array
%   Measured complex S-parameters in the frequency domain

%%


rawData = dlmread(fPath);  % Read the .txt file into an arr

[nFreqs, nAntPos] = size(rawData);  % Find num freqs, antenna positions

nAntPos = nAntPos / 2;  % Correct the number of antenna positions

fdData = complex(zeros([nFreqs, nAntPos]));  % Init arr to return

for antPos = 1 : nAntPos  % For each antenna position
    
    % Combine the real and imag parts from the .txt file 
    fdData(:, antPos) = rawData(:, 2 * antPos - 1) ... 
                        + 1j * rawData(:, 2 * antPos);
    
end  % End loop over antenna positions

end  % End func defintion
